"""add read_flag

Revision ID: f92d8f098403
Revises: f55ee08ef6e3
Create Date: 2018-01-04 20:58:24.805390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f92d8f098403'
down_revision = 'f55ee08ef6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notify', sa.Column('read_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notify', 'read_flag')
    # ### end Alembic commands ###
